// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./../src/components/AppLink.vue')['default']
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Featured: typeof import('./../src/components/Featured.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Moments: typeof import('./../src/components/Moments.vue')['default']
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    Posts: typeof import('./../src/components/Posts.vue')['default']
    Project: typeof import('./../src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
